name: CI
# This workflow is triggered on pushes to the repository.
on:
  [push]
#  push:
#    branches:
#      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [^1.14.0]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./... --coverage

  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go-version: [^1.14.0]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make build

#jobs:
#  build:
#    # Job name is Greeting
#    name: Greeting
#    # This job runs on Linux
#    runs-on: ubuntu-latest
#    steps:
#      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
#      - name: Hello world
#        uses: actions/hello-world-javascript-action@v1
#        with:
#          who-to-greet: 'Mona the Octocat'
#        id: hello
#      # This step prints an output (time) from the previous step's action.
#      - name: Echo the greeting's time
#        run: echo 'The time was ${{ steps.hello.outputs.time }}.'